version: "2.1"
services:
  jobmanager:
    container_name: ${USER}_jobmanager
    image: flink
    expose:
      - "6123"
    ports:
      - "8081"

    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    container_name: ${USER}_taskmanager
    image: flink
    expose:
      - "6121"
      - "6122"
    ports:
      - "18082"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
